name: flutter_sigma
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1  # Versão estável atual
  firebase_auth: ^5.3.4  # Versão compatível
  cloud_firestore: ^5.5.1
  dio: ^5.7.0
  logging: ^1.0.2
  logger: ^2.5.0
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.20.1
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  url_launcher: ^6.0.20
  vector_graphics: ^1.1.15
  vector_graphics_compiler: ^1.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Atualizado para a versão mais recente

# Dependências transitivas atualizadas
dependency_overrides:
  async: ^2.12.0
  boolean_selector: ^2.1.2
  characters: ^1.3.1
  clock: ^1.1.2
  collection: ^1.19.1
  fake_async: ^1.3.2
  http_parser: ^4.1.1
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  stack_trace: ^1.12.0
  string_scanner: ^1.4.0
  test_api: ^0.7.3
  vm_service: ^14.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
