name: flutter_sigma
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0  # Versão estável atual
  firebase_auth: ^5.3.4  # Versão compatível
  cloud_firestore: ^5.6.0
  dio: ^5.7.0
  logging: ^1.3.0
  logger: ^2.5.0
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.20.1
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.0.16
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  vector_graphics: ^1.1.15
  vector_graphics_compiler: ^1.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 
  flutter_launcher_icons: ^0.14.2

# Dependências transitivas atualizadas
dependency_overrides:
  async: ^2.12.0
  boolean_selector: ^2.1.2
  characters: ^1.4.0
  clock: ^1.1.2
  collection: ^1.19.1
  fake_async: ^1.3.2
  http_parser: ^4.1.1
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  string_scanner: ^1.4.1
  test_api: ^0.7.4
  vm_service: ^15.0.0
  source_span: ^1.10.1
  stream_channel: ^2.1.3
  term_glyph: ^1.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/imagemSetupGamer.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # Caminho para o ícone que deseja usar
