// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB12legd6-aXS2xFtHHqRAY3aqdoFOy2IQ',
    appId: '1:870701498948:web:545ebcaa9ce6e75a997211',
    messagingSenderId: '870701498948',
    projectId: 'projeto-frontsigma',
    authDomain: 'projeto-frontsigma.firebaseapp.com',
    storageBucket: 'projeto-frontsigma.appspot.com',
    measurementId: 'G-JJWHJZ87NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh1hu_le5Xy6zZ8a6OOC8UlYcynd28M9o',
    appId: '1:870701498948:android:00da6df950b0b1fe997211',
    messagingSenderId: '870701498948',
    projectId: 'projeto-frontsigma',
    storageBucket: 'projeto-frontsigma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZlv_IYalry1wjA2q6P_bBqqT5uS4L-jY',
    appId: '1:870701498948:ios:f8c90026468f87d5997211',
    messagingSenderId: '870701498948',
    projectId: 'projeto-frontsigma',
    storageBucket: 'projeto-frontsigma.appspot.com',
    iosBundleId: 'com.example.flutterSigma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZlv_IYalry1wjA2q6P_bBqqT5uS4L-jY',
    appId: '1:870701498948:ios:f8c90026468f87d5997211',
    messagingSenderId: '870701498948',
    projectId: 'projeto-frontsigma',
    storageBucket: 'projeto-frontsigma.appspot.com',
    iosBundleId: 'com.example.flutterSigma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB12legd6-aXS2xFtHHqRAY3aqdoFOy2IQ',
    appId: '1:870701498948:web:a9d880e87d06f580997211',
    messagingSenderId: '870701498948',
    projectId: 'projeto-frontsigma',
    authDomain: 'projeto-frontsigma.firebaseapp.com',
    storageBucket: 'projeto-frontsigma.appspot.com',
    measurementId: 'G-S52PC705SZ',
  );
}
